window.PRIVACY_EN = `PRIVACY POLICY
TruthMirror
Effective date: 19 May 2026
Version: 2026-05-19

1. INTRODUCTION

This Privacy Policy explains how Social Media Group SRL ("we", "us", "our") collects, uses, stores, and protects your personal data when you use the TruthMirror mobile application and website ("App", "Service").

We are committed to protecting your privacy and complying with the EU General Data Protection Regulation (GDPR), Romanian Law 190/2018, and applicable data protection laws.

Data Controller:
Social Media Group SRL
Bucharest, Romania
Email: truthmirrorapp@gmail.com

2. WHAT DATA WE COLLECT

2.1 Data you provide:
- Year of birth (for age verification only — we store the year, not your full date of birth)
- The text content of your conversations with the AI
- Your language preference
- Your subscription tier and status

2.2 Data generated by the Service:
- AI responses to your messages
- Detected behavioural pattern tags (e.g., "avoidance", "intellectualizing")
- Honesty Score and statistics computed from your conversations
- Timestamps of your activity
- An anonymous user identifier generated on your device

2.3 Data we do NOT collect:
- Your real name (unless you voluntarily include it in conversation text)
- Your email address (unless you contact us or join the waitlist)
- Your precise location
- Your contacts, photos, or other device data
- Payment card details (handled entirely by Apple/Google)

3. HOW WE USE YOUR DATA

We process your data to:
(a) provide the core Service — generate AI responses, detect patterns, compute statistics;
(b) maintain your conversation history and let you review your evolution over time;
(c) enforce daily question limits according to your subscription tier;
(d) verify you meet the 18+ age requirement;
(e) provide customer support when you contact us;
(f) comply with legal obligations.

Legal bases under GDPR (Article 6):
- Performance of a contract (providing the Service you subscribed to);
- Your consent (which you give during onboarding and may withdraw at any time);
- Our legitimate interests (improving and securing the Service);
- Compliance with legal obligations.

4. WE DO NOT TRAIN AI ON YOUR DATA

We do NOT use your conversation content to train, fine-tune, or improve any AI model. We do NOT sell, rent, or share your conversation content with advertisers or data brokers.

5. DATA STORAGE AND LOCATION

5.1 On-device: Your conversation history is stored locally on your device.

5.2 On our server: To provide cross-device features and enforce limits, conversation data, pattern statistics, and your profile are stored in our database hosted by Supabase in the European Union (Frankfurt, Germany).

5.3 AI processing: When you send a message, its text is transmitted to Anthropic PBC (United States), the provider of the Claude AI model, solely to generate a response. See section 11 below regarding international transfers.

6. THIRD-PARTY PROCESSORS

We share data only with the following processors, strictly to operate the Service:

(a) Supabase — database and backend hosting (EU). Stores conversation history, profiles, statistics.

(b) Anthropic PBC — AI model provider (US). Receives your message text to generate AI responses. Anthropic does not use API inputs to train its models.

(c) Apple / Google — subscription and payment processing. We never receive your full payment card details.

Each processor is bound by a data processing agreement consistent with GDPR Article 28.

7. DATA RETENTION

- Free (Glimpse) tier: conversation history is retained for 7 days, then automatically deleted.
- Paid tiers: conversation history is retained for the duration of your subscription plus 30 days, unless you delete it sooner.
- Pattern statistics and scores: retained while your account is active.
- If you delete your data or your account becomes inactive for 24 months, we delete all associated data.

8. YOUR RIGHTS UNDER GDPR

You have the right to:
(a) ACCESS — request a copy of your personal data;
(b) RECTIFICATION — correct inaccurate data;
(c) ERASURE — request deletion of your data ("right to be forgotten");
(d) RESTRICTION — limit how we process your data;
(e) PORTABILITY — receive your data in a portable format;
(f) OBJECTION — object to processing based on legitimate interests;
(g) WITHDRAW CONSENT — at any time, without affecting prior lawful processing.

You can exercise rights (c) and (e) directly in the App:
- Settings → "Delete all my data" deletes everything immediately.
- PDF export (on paid tiers) provides portability.

To exercise any other right, email truthmirrorapp@gmail.com. We respond within 30 days.

You also have the right to lodge a complaint with the Romanian Data Protection Authority (ANSPDCP) or your local supervisory authority.

9. DATA SECURITY

We implement appropriate technical and organisational measures to protect your data, including:
- Encryption in transit (HTTPS/TLS) and at rest;
- Our AI provider key is stored only on the server, never in the App;
- Access controls and authentication on our backend;
- Regular security review of our infrastructure.

No system is completely secure. We recommend you avoid including highly sensitive identifying details (full name, address, ID numbers) in conversation text.

10. CHILDREN'S PRIVACY

TruthMirror is strictly for users 18 and older. We do not knowingly collect data from anyone under 18. If we discover that we have collected data from a minor, we will delete it immediately. The App uses an automated computation of pattern statistics. These computations do not produce legal or similarly significant decisions about you. You always retain control of how to interpret or act on App output.

11. INTERNATIONAL TRANSFERS

As stated in section 5.3, conversation data is transferred to Anthropic in the United States under Standard Contractual Clauses. We have assessed this transfer and consider it provides adequate protection under GDPR Chapter V. You can request a copy of the relevant safeguards by contacting truthmirrorapp@gmail.com.

12. CHANGES TO THIS POLICY

We may update this Privacy Policy from time to time. We will notify you of material changes through the App. The "effective date" at the top will indicate the latest revision.

13. CONTACT

For privacy questions or to exercise your GDPR rights, contact:
Social Media Group SRL
Bucharest, Romania
truthmirrorapp@gmail.com

Romanian Data Protection Authority (ANSPDCP):
www.dataprotection.ro
B-dul G-ral. Gheorghe Magheru 28-30, Sector 1, Bucharest, Romania
`;