window.TERMS_EN = `TERMS OF SERVICE

Effective date: 11 May 2026
Version: 2026-05-11

These Terms of Service ("Terms") govern your use of the TruthMirror mobile application ("App"). By creating an account or using the App you confirm you have read, understood, and accept these Terms in full. If you do not accept these Terms, do not use the App.

1. WHO WE ARE
The App is operated by Social Media Group SRL, a company registered in Romania, with its registered office in Bucharest, Romania ("we", "us"). You can contact us at truthmirrorapp@gmail.com. Our website is truthmirror.net.

2. ELIGIBILITY
The App is only available to users aged 18 and over. By using the App you confirm that you are at least 18 years old. We may, at any time, ask for proof of age. If we believe you are under 18, we will terminate your access without notice and refund any unused subscription amounts pro rata, as required by applicable law.

3. WHAT THE APP IS — AND IS NOT
3.1 The App is a self-reflection tool powered by artificial intelligence. It is designed to help adult users examine their own thoughts, behaviours, and patterns by providing direct, non-advisory feedback.
3.2 THE APP IS NOT A MEDICAL DEVICE, A HEALTHCARE SERVICE, A PSYCHOTHERAPY SERVICE, A COUNSELLING SERVICE, OR A CRISIS HOTLINE. The App does not provide medical, psychiatric, psychological, legal, or financial advice. It must not be used as a substitute for professional care.
3.3 Responses generated by the App are produced by an artificial intelligence language model. They may be inaccurate, incomplete, inappropriate, or harmful. You must use your own judgement when interpreting and acting on any response.
3.4 The App must not be used by individuals experiencing a mental health crisis, suicidal ideation, thoughts of self-harm, harm to others, or symptoms of severe psychiatric illness. If you are in crisis, contact your local emergency services or a recognised crisis line immediately. See the Crisis Support resources within the App.

4. ACCOUNT AND DATA
4.1 You are responsible for the security of the device on which the App is installed and for all activity carried out through the App on that device.
4.2 Conversations are primarily stored locally on your device. We may offer optional encrypted cloud synchronisation in future versions.
4.3 We process personal data in accordance with our Privacy Policy, which forms part of these Terms.

5. SUBSCRIPTIONS, PAYMENTS, AND REFUNDS
5.1 The App offers free and paid tiers. Free tier provides a limited number of interactions per day. Paid tiers are sold via Apple App Store and Google Play and are subject to their respective billing terms.
5.2 Subscriptions renew automatically until cancelled. You can manage and cancel your subscription through your Apple ID or Google Play account settings.
5.3 For consumers in the European Union, you have the right to withdraw from a new subscription within 14 days of purchase without giving any reason, in accordance with Directive 2011/83/EU. To exercise this right, contact truthmirrorapp@gmail.com or use the refund process of the relevant app store. The withdrawal right may be lost if the digital service has been substantially used within that period, where you have given express prior consent and acknowledgement of the loss of the right.
5.4 We do not provide refunds outside the conditions described in section 5.3 except where required by law.

6. ACCEPTABLE USE
You agree not to:
(a) use the App in violation of any law;
(b) attempt to reverse engineer, decompile, or extract the source code of the App;
(c) attempt to circumvent rate limits, paywalls, or security mechanisms;
(d) use automated tools or scripts to interact with the App;
(e) use the App to generate content that is illegal, abusive, defamatory, harmful, or that infringes the rights of others;
(f) resell, sublicense, or commercially exploit access to the App;
(g) use the App for any purpose other than personal self-reflection.
We may suspend or terminate your access if we reasonably believe you have breached this section.

7. INTELLECTUAL PROPERTY
The App, its design, code, models, prompts, and branding are owned by us or our licensors. Conversations you generate remain your content; you grant us a limited, non-exclusive licence to process them in order to operate the service, including transmitting them to AI providers for response generation. We do not use your conversations to train AI models.

8. AI LIMITATIONS AND DISCLAIMERS
8.1 The App generates output using large language models (currently provided by Anthropic). These models can produce inaccurate, biased, or harmful content despite our safeguards.
8.2 You acknowledge that AI responses are probabilistic, not authoritative, and must not be relied upon for any consequential decision.
8.3 The App may be unavailable due to maintenance, updates, third-party outages, or technical failures. We do not guarantee uninterrupted access.

9. LIMITATION OF LIABILITY
9.1 To the maximum extent permitted by applicable law, our total cumulative liability arising out of or in connection with the App is limited to the amount you have paid to us for the App in the twelve (12) months preceding the event giving rise to the claim.
9.2 We exclude liability for indirect, incidental, special, consequential, or punitive damages, including loss of profits, loss of data, loss of goodwill, or psychological harm, except where such exclusion is prohibited by law.
9.3 Nothing in these Terms excludes liability for death or personal injury caused by our negligence, for fraud, or for any other liability that cannot be excluded under applicable law.
9.4 The App is provided "as is" and "as available" without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement, to the maximum extent permitted by law.

10. TERMINATION
10.1 You may stop using the App at any time. You may delete your data and account through the in-app settings.
10.2 We may suspend or terminate your access if you breach these Terms, if we reasonably suspect fraud or abuse, or if we discontinue the App. We will give reasonable notice where practicable.

11. CHANGES TO THESE TERMS
We may update these Terms from time to time. If we make material changes, we will notify you through the App or via the contact details associated with your account, and you will be asked to accept the updated Terms before continuing to use the App.

12. GOVERNING LAW AND DISPUTES
12.1 These Terms are governed by Romanian law, without prejudice to mandatory consumer protections available to you under the law of your country of residence.
12.2 Any dispute arising out of or in connection with these Terms shall be submitted to the competent courts of Bucharest, Romania, except where mandatory law grants you the right to bring proceedings in the courts of your country of residence.
12.3 Consumers in the European Union may also use the European Commission Online Dispute Resolution platform: https://ec.europa.eu/consumers/odr

13. CONTACT
For any question, complaint, or legal request related to these Terms, contact:
Social Media Group SRL
Bucharest, Romania
truthmirrorapp@gmail.com

By using the App you confirm that you have read and understood these Terms and that you accept them in full.`;