window.TERMS_EN = `TERMS OF SERVICE
TruthMirror
Effective date: 28 May 2026
Version: 2026-05-28

1. WHO WE ARE

The TruthMirror mobile application and website ("App", "TruthMirror", "Service") are operated by:

Social Media Group SRL
Registered office: Bucharest, Romania
Contact: support@truthmirror.net
Website: https://truthmirror.net

For purposes of these Terms, "we", "us", and "our" refer to Social Media Group SRL.

2. ACCEPTANCE OF THESE TERMS

By creating an account, installing the App, or otherwise using the Service, you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree, do not use the Service.

You must affirmatively accept these Terms during the in-app onboarding flow before you may use TruthMirror.

3. AGE REQUIREMENT — 18+

TruthMirror is intended exclusively for adults aged 18 years or older. You must confirm your date of birth during onboarding and you must not use the Service if you are under 18.

If we become aware that a user is under 18, we will terminate their access and delete associated data without prior notice.

4. NATURE OF THE SERVICE — IMPORTANT

TruthMirror is an AI-powered self-reflection tool. The App uses large language models to ask you questions about avoidance, self-deception, and behavioural patterns, based on text you provide.

TruthMirror is NOT:
(a) a medical device, mental-health treatment, or therapy service;
(b) a substitute for professional mental-health, psychological, or psychiatric care;
(c) emergency or crisis intervention;
(d) legal, financial, or relationship advice;
(e) a diagnostic tool.

The Service is provided for personal reflection and self-awareness. You acknowledge that AI responses may be inaccurate, inappropriate, or unsuitable for your situation, and you assume full responsibility for any decisions you make. Any score or metric generated by the App (for example, the clarity score / "Honesty Score") is an AI-generated interpretive metric intended solely for self-reflection, and does not constitute a scientific, medical, psychiatric, or psychological evaluation.

If you are experiencing a mental health crisis, suicidal thoughts, or are in danger to yourself or others, stop using the App and contact emergency services in your country (e.g., 112 in the EU, 988 in the United States, 116 123 in the UK) or visit findahelpline.com.

5. SUBSCRIPTION TIERS AND PRICING

5.1 We offer the following tiers:

GLIMPSE (FREE):
- 3 AI questions per day
- Basic pattern detection
- 7 days history retention
- Crisis resources
- Share cards (images with the mirror's reply)
- Available in English, Romanian, Spanish, and Japanese

REFLECTION (€4.99/month or €49/year):
- 20 AI questions per day
- Everything in Glimpse
- Full conversation history
- Pattern Evolution chart
- Honesty Score tracking
- Daily reminder
- Streak counter
- 3 separate contexts
- PDF export (1/month)

MIRROR (€9.99/month or €99/year):
- 40 AI questions per day
- Everything in Reflection
- Weekly Insights Report
- Unlimited PDF export
- Conversation tagging
- Custom personality settings
- 6 separate contexts
- Priority support

TRUTH (€19.99/month or €199/year) — Launching approximately 6 months after public release:
- Unlimited AI questions (subject to fair use)
- Everything in Mirror
- Voice mode (talk to the AI)
- Monthly deep analysis report

5.2 Annual subscriptions provide approximately 2 months free compared to monthly billing.

5.3 Prices may change with at least 30 days' prior notice. Existing subscribers will be notified through the App and/or email. Price changes do not apply to your current billing period.
5.4 Fair use. Plans with "unlimited" questions are intended for personal, individual, good-faith use. To protect the Service and other users, we reserve the right to apply reasonable abuse-prevention measures — for example, in cases of automation, unauthorized programmatic access, account sharing among multiple people, resale, or a volume of usage clearly disproportionate to normal human use. In such cases we may temporarily rate-limit usage, contact the user, or, in serious cases, suspend the account, in accordance with section 10 (Acceptable Use).


6. FREE TRIAL

6.1 Paid tiers (Reflection and Mirror) include a 7-day free trial.

6.2 If you do not cancel before the trial ends, you will be charged automatically at the standard rate.

6.3 Each user is entitled to one free trial per tier. Repeated trial abuse may result in trial denial.

7. BILLING, AUTO-RENEWAL, AND REFUNDS

7.1 Subscriptions are purchased and billed through Apple App Store or Google Play, subject to their respective terms.

7.2 Subscriptions auto-renew unless cancelled at least 24 hours before the end of the current billing period. Manage your subscription in:
- iOS: Settings → Apple ID → Subscriptions → TruthMirror
- Android: Google Play → Profile → Payments & subscriptions

7.3 30-DAY MONEY-BACK GUARANTEE. If TruthMirror does not meet your expectations, you may request a full refund within 30 days of your first paid charge by emailing support@truthmirror.net with your transaction ID. Refunds are processed within 5 business days through the original payment method. No reason required. We reserve the right to deny abusive, fraudulent, or repeated refund requests.

7.4 EU CONSUMER WITHDRAWAL. EU/EEA consumers have a statutory right to withdraw from contracts for digital services within 14 days of purchase. To exercise this right, contact support@truthmirror.net. By starting to use the Service immediately upon purchase, you may waive this right in accordance with Article 16(m) of Directive 2011/83/EU.

7.5 The 30-day money-back guarantee in section 7.3 is in addition to, not in place of, your statutory rights under EU consumer law.

8. CANCELLATION

You may cancel your subscription at any time, with no reason required, through your App Store or Google Play account settings. Cancellation takes effect at the end of the current billing period; you retain access to paid features until then. We do not use retention tactics, exit surveys, or friction to discourage cancellation.

9. NO ADVERTISING

TruthMirror does not display advertisements and we will not introduce advertising into the Service. The Service is funded entirely by subscription revenue.

10. ACCEPTABLE USE

You agree not to:
(a) use the Service for any illegal purpose or to facilitate illegal activity;
(b) attempt to extract, reverse-engineer, or copy our AI models, prompts, or system architecture;
(c) submit content depicting or threatening violence, abuse, sexual content involving minors, or self-harm to others;
(d) use the Service to harass, stalk, or harm any person;
(e) attempt to circumvent rate limits, payment systems, or access controls;
(f) impersonate another person or misrepresent your age or identity;
(g) use automated systems (bots, scrapers) to access the Service;
(h) share your account credentials with others.

We reserve the right to suspend or terminate accounts violating these rules, with or without notice.

11. CONTENT YOU PROVIDE

You retain ownership of the text you write into TruthMirror ("Your Content"). By using the Service, you grant us a limited, non-exclusive license to process Your Content solely to provide the Service to you (generating AI responses, detecting patterns, computing statistics, storing conversation history).

We do NOT use Your Content to train AI models. We do NOT sell Your Content to any third party. See our Privacy Policy for full data-handling details.

Content distribution: The App lets you export conversations as PDF (on paid plans) and create share cards containing replies of the mirror. These files are generated locally and leave your device only through your explicit action. You are solely responsible for the content you choose to distribute and for the consequences of distributing it, including towards third parties. Distributed mirror replies remain subject to section 12 (AI-Generated Content).

12. AI-GENERATED CONTENT

AI responses produced by the Service may be incorrect, biased, or inappropriate. The App uses third-party AI models (Anthropic Claude) which are subject to their own limitations. We make no warranty as to the accuracy, completeness, or fitness for purpose of any AI output.

You are solely responsible for evaluating AI responses critically and for any actions you take in reliance on them.

13. INTELLECTUAL PROPERTY

All rights to the App, including its design, code, brand, name "TruthMirror", logos, system prompts, and audio features, are owned by Social Media Group SRL. You receive a limited, non-transferable, revocable license to use the App for personal, non-commercial purposes only.

14. LIMITATION OF LIABILITY

14.1 To the maximum extent permitted by applicable law, the Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, express or implied.

14.2 We are not liable for:
(a) any decision you make based on AI output;
(b) emotional, psychological, or physical consequences of using the Service;
(c) data loss due to technical failure — we recommend exporting your data and creating encrypted backups regularly; you alone hold the backup recovery code, and we cannot recover your backup or its code if you lose it;
(d) service interruptions, errors, or downtime;
(e) third-party services (Apple, Google, Anthropic) on which we depend;
(f) loss of content stored on your device if you lose, damage, replace, or reset your device without a valid backup, or if you lose your backup recovery code.

14.3 Our maximum aggregate liability to you in any 12-month period is limited to the amount you paid us for the Service in the preceding 12 months, or €100, whichever is greater.

14.4 Nothing in these Terms limits liability for (i) gross negligence or wilful misconduct, (ii) death or personal injury caused by our negligence, or (iii) any other liability that cannot be limited under applicable law.

15. CHANGES TO THESE TERMS

We may update these Terms from time to time. If we make material changes, we will notify you through the App or via the contact details associated with your account, and you will be asked to accept the updated Terms before continuing to use the App.

16. GOVERNING LAW AND DISPUTES

16.1 These Terms are governed by Romanian law, without prejudice to mandatory consumer protections available to you under the law of your country of residence.

16.2 Any dispute arising out of or in connection with these Terms shall be submitted to the competent courts of Bucharest, Romania, except where mandatory law grants you the right to bring proceedings in the courts of your country of residence.

16.3 Consumers in the European Union may also use the European Commission Online Dispute Resolution platform: https://ec.europa.eu/consumers/odr

17. APP STORES (APP STORE AND GOOGLE PLAY)

When you download TruthMirror from the Apple App Store or Google Play, the following additional provisions apply:

17.1 These Terms are concluded solely between you and Social Media Group SRL, and not with Apple Inc. or Google LLC. Social Media Group SRL, not Apple or Google, is solely responsible for the App and its content.

17.2 Apple and Google have no obligation whatsoever to furnish any maintenance or support services for the App. Any support requests must be directed to us at support@truthmirror.net.

17.3 If the App fails to conform to any applicable warranty, you may notify Apple, and Apple may refund the purchase price of the App (if any); to the maximum extent permitted by law, Apple will have no other warranty obligation whatsoever with respect to the App. For Google Play purchases, Google's refund policy applies.

17.4 Apple and Google are not responsible for addressing any claims by you or any third party relating to the App, including but not limited to: (a) product liability claims; (b) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (c) claims arising under consumer protection or similar legislation.

17.5 In the event of any third-party claim that the App or your use of it infringes that third party's intellectual property rights, Social Media Group SRL, not Apple or Google, will be solely responsible for the investigation, defense, settlement and discharge of any such claim.

17.6 Apple, Google and their subsidiaries are third-party beneficiaries of these Terms, and upon your acceptance of these Terms, they will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third-party beneficiary.

17.7 You must also comply with the applicable third-party terms of service when using the App (for example, the App Store or Google Play terms).

18. CONTACT

For any question, complaint, or legal request related to these Terms, contact:

Social Media Group SRL
Bd. Decebal 12, București, România
Company ID (CUI): 42636861 · Trade Register: J40/6444/2020
Email: support@truthmirror.net

By using the App, you confirm that you have read and understood these Terms and that you accept them in full.
`;